

admin:
    port: -1
    debug: false
    password: 12345

model:
    # sqlite or mysql
    dbtype: "mysql"    
    # data.db or root:wLei6700413@@tcp(127.0.0.1:3306)/media_nvr?charset=utf8mb4&parseTime=True&loc=Local
    dbsource: "root:wLei6700413@@tcp(127.0.0.1:3306)/test_db?charset=utf8mb4&parseTime=True&loc=Local"






